version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  currency_service:
    build:
      context: ./currency_service
    container_name: currency_service
    depends_on:
      - redis

  bot:
    build:
      context: ./bot
    container_name: bot
    depends_on:
      - redis
